### ISSUE TITLE
Please add syntax highlighting for .list files like sources.list

### ISSUE THREAD

**Issue by alan-wint** [nthykier/IDEA-debpkg#114]
**Is your feature request related to a problem? Please describe.**
No related problem.

**Describe the solution you'd like**
sources.list files would have syntax highlighting.

**Describe alternatives you've considered**
No clear alternative.

**Additional context**
Example highlighting in Nano
![image](https://user-images.githubusercontent.com/70092135/216151066-58bfd134-a9f6-4dc1-b1bd-cbc0c173fdc0.png)

**Comment by nthykier** [comment]
Thanks for your suggestion.

I will add some basic syntax highlighting in the next version to be uploaded "soon".

Apologies for the late reply. My notification settings were not optimal and I have fixed them now.
